import type { Metadata } from "next";
import "../public/assets/css/styles.css";

export const metadata: Metadata = {
  title: "Hyper Energy Bar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/sbg8hhu.css"/>
        <link rel="icon" href="/assets/img/favicon.png" type="image/png" />
      </head>
      <body>{children}</body>
    </html>
  );
}
